api/actions/urls.py
from django.urls import path, include
from django.views.generic.base import RedirectView, TemplateView
#from rest_framework import routers
#from rest_framework.documentation import include_docs_urls
from . import views

# Routers
#router = routers.DefaultRouter()
#router.register(r'api', views.OldActionViewSet)

app_name = 'actions'
urlpatterns = [
    path('<int:action_pk>/', views.pkdetail, name="pkdetail"),
    path('available/', views.ActionsListView.as_view(list_type='available'),
         name="available"),
    path('completed/', views.ActionsListView.as_view(list_type='completed'),
         name="completed"),
    path('coordinator/', views.CoordinatorDashboardView.as_view(), name="coordinator_dashboard"),
    path('coordinator/actions/', views.CoordinatorActionsView.as_view(), name="coordinator_actions"),
    path('coordinator/call/', views.CoordinatorCallView.as_view(), name="coordinate_actions"),
    path('coordinator/call/add/', views.CoordinatorCreateActionReferralView.as_view(), name="add_actions"),
    path('coordinator/action/', views.CoordinatorSingleActionView.as_view(), name="single_action"),
    path('ongoing/', views.ActionsListView.as_view(
        list_type='ongoing'), name="ongoing"),
    path('<action_uuid>/complete/', views.action_feedback, name="complete"),
    path('<action_uuid>/cancel/',
         views.stop_ongoing, name="cancel"),
#    path('api/', include((router.urls, 'app_name'))),
#    path('swagger-ui/', TemplateView.as_view(
#        template_name='api/swagger_ui.html',
#        extra_context={'schema_url':'openapi-schema'}),
#        name='swagger-ui'),
#    path('docs/', include_docs_urls(title='My API service'), name='api-docs'),
    path('<action_uuid>/', views.detail, name="detail"),
    path('', RedirectView.as_view(url='/'), name='index'),
]

api/tofro/urls.py
"""tofro URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from decorator_include import decorator_include
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from rest_framework.schemas import get_schema_view
from rest_framework import routers
from rest_framework.documentation import include_docs_urls


from tofro.views import LoginView, LogoutView, PasswordResetConfirmView, ToFroPasswordResetView, homepage, resolve_static_path_view
from tofro.lib import login_required
from users.views import UserSettingsView
from actions.views import ActionViewSet, ReferralViewSet, OrganisationViewSet, ActionFeedbackViewSet
from users.views import VolunteerViewSet, CoordinatorViewSet, ResidentViewSet, CurrentCoordinatorViewSet
from categories.views import HelpTypeViewSet, RequirementViewSet, WardViewSet, ReferralTypeViewSet

router2 = routers.SimpleRouter()
router2.register(r'actions', ActionViewSet)
router2.register(r'action_feedback', ActionFeedbackViewSet)
router2.register(r'referrals', ReferralViewSet)
router2.register(r'organisations', OrganisationViewSet)
router2.register(r'volunteers', VolunteerViewSet)
router2.register(r'coordinators', CoordinatorViewSet)
router2.register(r'current_coordinator', CurrentCoordinatorViewSet, basename='CurrentCoordinator')
router2.register(r'residents', ResidentViewSet)
router2.register(r'helptypes', HelpTypeViewSet)
router2.register(r'referraltypes', ReferralTypeViewSet)
router2.register(r'requirements', RequirementViewSet)
router2.register(r'wards', WardViewSet)

admin_path = settings.DJANGO_ADMIN_LOCATION + '/'

urlpatterns = [
    path('', homepage, name="home"),
    re_path(r'static-path/(?P<path>.+)', resolve_static_path_view),
    path(admin_path, admin.site.urls, name="admin"),
    # Take over the password reset confirmation with our own view
    path('accounts/reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password_reset/',
         ToFroPasswordResetView.as_view(), name='password_reset'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include((router2.urls, 'app_name'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('actions/', decorator_include(login_required, ('actions.urls', 'actions'))),
    path('accounts/login', LoginView.as_view(), name="login"),
    path('accounts/logout', LogoutView.as_view(), name="logout"),
    path('accounts/settings', UserSettingsView.as_view(), name='user-settings'),
    path('notifications/', include('notifications.urls')),
    path('docs/', include_docs_urls(title='My API service'), name='api-docs'),
    path('openapi', get_schema_view(
        title="Your Project",
        description="API for all things …",
        #permission_classes='IsAdminUser',
        version="1.0.0",
        url='/',
    ), name='openapi-schema'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + [
    re_path(r'^(?P<url>.*/)$', flatpage, name="page"),
]


# Add the debug toolbar.
if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

# Add Redis URLs.
urlpatterns += [
    path('django-rq/', include('django_rq.urls'))
]

api/actions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from django.utils import timezone
from django.views import generic
from django.urls import reverse
from rest_framework import viewsets, mixins
from rest_framework.decorators import action

from django.contrib.auth.mixins import UserPassesTestMixin, AccessMixin
from django.contrib.auth.decorators import user_passes_test

from core.views import BaseToFroViewSet, IsInMixin
from users.models import volunteer_check

from .models import Action, ActionStatus, ActionFeedback, Referral, Organisation
from .forms import ActionFeedbackForm, ActionCancellationForm
from .serializer import ActionSerializer, ReferralSerializer, OrganisationSerializer, ActionFeedbackSerializer

from django.core.exceptions import ValidationError
from datetime import datetime

import logging
logger = logging.getLogger(__name__)

LIST_DEFINITIONS = {
    'available': {
        'title': "Here's what you can do to help",
        'heading': "Here's what you can do to help",
        'queryset': lambda volunteer:
            volunteer.available_actions.order_by(
                'requested_datetime', '-action_priority')
    },
    'completed': {
        'title': "Your completed actions",
        'heading': "Your completed actions",
        'queryset': lambda volunteer:
            volunteer.completed_actions.order_by(
                'requested_datetime', '-action_priority')
    },
    'ongoing': {
        'title': "Your ongoing actions",
        'heading': "Your ongoing actions",
        'queryset': lambda volunteer:
            volunteer.ongoing_actions.order_by(
                'requested_datetime', '-action_priority'
            )
    },
    'mine': {
        'title': "Your upcoming actions",
        'heading': "Your upcoming actions",
        'queryset': lambda volunteer:
        # order first by action_status to make the assigned
        # actions appear first
        volunteer.upcoming_actions.order_by(
            '-action_status', 'requested_datetime', '-action_priority')
    }
}

def volunteer_check(user):
    return user.is_volunteer

class ActionViewSet(IsInMixin, mixins.UpdateModelMixin, BaseToFroViewSet):
    queryset = Action.objects.all()
    serializer_class = ActionSerializer
    ordering = '-pk'


class ActionFeedbackViewSet(IsInMixin, BaseToFroViewSet):
    queryset = ActionFeedback.objects.all()
    serializer_class = ActionFeedbackSerializer
    ordering = '-pk'

    @action(methods=['get'], detail=False, url_path='volunteerin/(?P<pks>[0-9,]+)')
    def volunteerin( self, request, pks=None ):
        pks = pks.split(',')
        pks = [int(pk) for pk in pks]
        self.queryset = self.queryset.filter(volunteer__in=pks)
        #print(self.queryset.count())
        return self.list(request)


class ReferralViewSet(mixins.UpdateModelMixin, BaseToFroViewSet):
    queryset = Referral.objects.all()
    serializer_class = ReferralSerializer
    ordering = '-pk'


class OrganisationViewSet(mixins.UpdateModelMixin, BaseToFroViewSet):
    queryset = Organisation.objects.all()
    serializer_class = OrganisationSerializer
    ordering = 'name'

class CoordinatorDashboardView(UserPassesTestMixin, AccessMixin, generic.TemplateView):
    template_name = 'actions/dashboard.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        return context

class CoordinatorActionsView(UserPassesTestMixin, AccessMixin, generic.TemplateView):
    template_name = 'actions/coordinator_actions.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        return context

class CoordinatorCallView(UserPassesTestMixin, AccessMixin, generic.TemplateView):
    template_name = 'actions/coordinator.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        return context


class CoordinatorCreateActionReferralView(UserPassesTestMixin, AccessMixin, generic.TemplateView):
    template_name = 'actions/create_action_referral.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        return context

class CoordinatorSingleActionView(UserPassesTestMixin, AccessMixin, generic.TemplateView):
    template_name = 'actions/single_action.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        return context

class ActionsListView(UserPassesTestMixin, AccessMixin, generic.ListView):

    def test_func(self):
        return volunteer_check(self.request.user)

    def get_permission_denied_message(self):
        return "You do not have permission to view that page"

    template_name = 'actions/index.html'
    context_object_name = 'actions'
    list_type = 'available'

    paginate_by = 20

    def get_queryset(self):
        volunteer = self.request.user.volunteer
        # Avoid N+1 queries when rendering the list of actions
        return LIST_DEFINITIONS[self.list_type]['queryset'](volunteer).select_related('help_type', 'resident', 'resident__ward')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['current_list_type'] = self.list_type
        context['title'] = LIST_DEFINITIONS[self.list_type]['title']
        context['heading'] = LIST_DEFINITIONS[self.list_type]['heading']
        return context


def back_url(action, volunteer):
    if (action.assigned_volunteers.filter(pk=volunteer.pk).exists()):
        return reverse('actions:available')

    if (action.action_status == ActionStatus.INTEREST or action.action_status == ActionStatus.ASSIGNED):
        return reverse('actions:index')

    if (action.action_status == ActionStatus.ONGOING):
        return reverse('actions:ongoing')

    if (action.action_status == ActionStatus.COULDNT_COMPLETE or action.action_status == ActionStatus.COMPLETED):
        return reverse('actions:completed')

    return reverse('actions:available')

@user_passes_test(volunteer_check)
def pkdetail(request, action_pk):
    action = get_object_or_404(Action, pk=action_pk)
    return redirect(action, permanent=True)

@user_passes_test(volunteer_check)
def detail(request, action_uuid):
    volunteer = request.user.volunteer
    try:
        action = Action.objects.get(action_uuid=action_uuid)
    except (ValidationError, Action.DoesNotExist):
        raise Http404()

    if request.method == "POST":
        if request.POST.get('_action') == 'contact':
            action.volunteer_made_contact_on = timezone.now()
            action.save()
        else:
            # Check if the action still needs volunteers to register interest.

            if request.POST.get('_action') == 'withdraw_help':
                if action.action_status == ActionStatus.PENDING \
                        or action.action_status == ActionStatus.INTEREST:

                    action.withdraw_interest_from(volunteer)
                    messages.info(
                        request, 'Noted! Sorry to hear you can no longer help.')

                else:
                    if (volunteer in action.assigned_volunteers.all()):
                        messages.error(request,
                                       'Sorry, looks like your help was already accepted. Please contact a coordinator make arrangements.')
                    # FIXED assigned_volunteer
            else:
                if action.action_status == ActionStatus.PENDING \
                        or action.action_status == ActionStatus.INTEREST:

                    action.register_interest_from(volunteer)
                    messages.success(request, 'Thanks for volunteering!')

                else:
                    messages.error(
                        request, 'Thanks, but someone has already volunteered to help')
        return redirect(action)

    context = {
        'action': action,
        'back_url': back_url(action, volunteer),
        'title': f"{str(action.help_type).title()} - {str(action.ward).title()} (Action no. {action.id})",
        'heading': action.description,
        'volunteer': volunteer
    }

    return render(request, 'actions/detail.html', context)

@user_passes_test(volunteer_check)
def stop_ongoing(request, action_uuid):
    return action_feedback(request, action_uuid, template_name="actions/stop_ongoing.html", Form=ActionCancellationForm, extra_context={
        'title': 'Your collaboration is stopping',
        'heading': 'Your collaboration is stopping'
    })

@user_passes_test(volunteer_check)
def action_feedback(request, action_uuid, template_name='actions/complete.html', Form=ActionFeedbackForm, extra_context={}):
    volunteer = request.user.volunteer
    try:
        action = Action.objects.get(action_uuid=action_uuid)
    except (ValidationError, Action.DoesNotExist):
        raise Http404()

    if not action.assigned_volunteers.filter(pk=volunteer.pk).exists() or not action.can_give_feedback:

api/actions/templates/actions/_action_footer_assigned_to_user.html
{% load svg %}

{% if action.checkin_required %}
  <h3 class="h5 text-center">
    Thanks for volunteering.</h3>
  <p>
    Please contact the person asap so they know they have a volunteer/buddy and to make the arrangements.
    We would recommend you shield your telephone number when doing this.
  </p>
  <div class="d-flex flex-wrap justify-content-around mt-n2">
    <a class="btn btn-link px-0 mt-2" href="{% url 'actions:complete' action.action_uuid%}">
      I went and helped!
    </a>
    <form method="POST" class="mt-2">
      {% csrf_token %}
      <button class="btn btn-primary" name="_action" value="contact">
        {% embed_fontawesome 'comments' icon_set="regular" %}
        I've made contact
      </button>
    </form>
  </div>
{% elif action.is_ongoing %}
  <h3 class="h5 text-center">
    You've arranged to help this person regularly.</h3>
  <p>
    Please let us know when you go and help them, or if your collaboration with them is stopping.
  </p>
  <div class="d-flex flex-wrap justify-content-around mt-n2">
    <a class="btn btn-link mt-2 px-0" href="{% url 'actions:cancel' action.action_uuid %}">
      This won't happen anymore.
    </a>
    <a class="btn btn-primary mt-2" href="{% url 'actions:complete' action.action_uuid %}">
      {% embed_fontawesome 'check' class_attribute="align-icon" %}
      I checked in with them!
    </a>
  </div>
{% else %}
  <a class="btn btn-primary d-table mx-auto mt-2" href="{% url 'actions:complete' action.action_uuid%}">
    {% embed_fontawesome 'check' class_attribute="align-icon" %}
    I went and helped!
  </a>
{% endif %}

api/actions/templates/actions/_action_footer_unassigned.html
{% load svg %}

{% if volunteer in action.interested_volunteers.all %}
  <p class="text-center">Please wait whilst we check things through. This is to maximise the privacy and safety of everyone involved. We'll be back in touch soon!</p>
  <form method="POST">
    {% csrf_token %}
    <button class="btn d-table mx-auto btn-outline-danger" name="_action" value="withdraw_help">
      Sorry, I can't help anymore.
    </button>
  </form>
{% else %}
  <form method="POST">
    {% csrf_token %}
    <button class="btn d-table mx-auto btn-primary" name="_action" value="accept_help">
      {% embed_fontawesome 'hands-helping' class_attribute="align-icon mr-1" %}
      I'll help!
    </button>
  </form>
{% endif %}

api/actions/templates/actions/_action_list_item.html
{% load humanize %}
{% load svg %}
{% load actions %}


<li class="
    list-group-item 
    list-group-item-action 
    action-list-item
    {% if action|is_awaiting_confirmation_for:user.volunteer %}
      text-muted
    {%endif%}
  ">
  <i class="btn btn-icon-only action-list-item__icon action-list-item__type" role="presentation">
    {% embed_fontawesome action.help_type.icon_name fallback='hands-helping'%}
  </i>
  <h3 class="h5 mb-1">
    <a class="action-list-item-link stretched-link" 
        href="{% url 'actions:detail' action.action_uuid %}"
        aria-labelledby="
        action_label_{{action.id}} 
        action_date_{{action.id}} 
        action_status_{{action.id}}">
      <span id="action_label_{{action.id}}">
        <strong>{{action.help_type}}</strong> <span class="text-muted h6 font-weight-normal">{{action.ward}}</span>
      </span>
    </a>
  </h3>
  <time datetime="{{action.requested_datetime|date:"c"}}" class="text-right">
    <span id="action_date_{{action.id}}">{{action.requested_datetime|date:"D d M"}}</span>
    <span class="text-muted small">({{action.requested_datetime|naturaltime}})</span>
  </time>
  {% if action|is_awaiting_confirmation_for:user.volunteer %}
    <i class="text-muted action-list-item__action" id="action_status_{{action.id}}">
      {% embed_fontawesome 'pause-circle' %}
      <span class="sr-only">Pending approval</span>
    </i>
  {% elif action.is_completed %}
    <i class="text-success action-list-item__action" id="action_status_{{action.id}}">
      {% embed_fontawesome 'check-circle'  %}
      <span class="sr-only">Completed</span>
    </i>
  {% elif action.is_failed%}
    <i class="text-danger action-list-item__action" id="action_status_{{action.id}}">
      {% embed_fontawesome 'times-circle' %}
      <span class="sr-only">Could not be completed</span>
    </i>
  {% comment %} {% else %}
    <i class="text-primary action-list-item__action" role="presentation" id="action_status_{{action.id}}">
      {% embed_fontawesome 'play-circle' %}
    </i> {% endcomment %}
  {% endif %}
</li>

api/actions/templates/actions/_problem_help.html
{% if action.is_partially_assigned or action.is_ongoing %}
    <p class="text-center text-muted small">
        No longer able to take on the action or encountering problems?
        Please email a co-ordinator at <a href="mailto:{{settings.COORDINATOR_EMAIL}}">{{settings.COORDINATOR_EMAIL}}</a>
    </p>
{% endif %}

api/actions/templates/actions/_resident_detail.html
{% load svg %}
{% load links %}

<article class="space-3 card p-3" aria-label="resident">
  <h3 class="h5">{{resident.first_name}} {{resident.last_name}}</h3>
  <a href="{{resident.address|map_url}}" target="_blank" rel="noreferrer noopener"
    class="with-decorative-button d-flex justify-content-between align-items-center space-x-3">
    <span>
      {{resident.address_line_1}}<br>
      {%if resident.address2 %}
      {{resident.address_line_2}}<br>
      {%endif%}
      {%if resident.address3 %}
      {{resident.address_line_3}}<br>
      {%endif%}
      {{resident.postcode}}
    </span>
    <span role="presentation" class="with-decorative-button__button btn btn-outline-info btn-icon-only rounded ml-3">
      {% embed_svg 'node_modules/@fortawesome/fontawesome-free/svgs/solid/map-marked-alt.svg' height=16 width=16 %}
    </span>
  </a>
  {% if resident.phone or resident.phone_secondary %}
  <div class="btn-group mx-n3 mb-n3">
    {% include 'shared/_phone_link.html' with phone_number=resident.phone %}
    {% include 'shared/_phone_link.html' with phone_number=resident.phone_secondary %}
  </div>
  {% endif %}

</article>

api/actions/templates/actions/complete.html
{% extends 'layouts/application.html' %}

{% load svg %}
{% load crispy_forms_tags %}

{% block 'content' %}
<form class="card p-3" method="POST">
  {% csrf_token %}
  {% crispy form form.helper%}
  <button name="outcome" value="ok" class="btn btn-primary d-table mx-auto mt-4">
    {% embed_fontawesome 'thumbs-up' icon_set='regular' class_attribute="align-icon mr-1" %}
    Send feedback
  </button>  
</form>
{% include './_problem_help.html' with action=action volunteer=volunteer%}
{% endblock %}

api/actions/templates/actions/coordinator.html
{% extends 'layouts/application.html' %}

{% load humanize %}
{% load actions %}
{% load static %}


{% block 'content' %}
<div id="selectCreate"></div>
<script type="text/javascript" src="{% static 'vue/dist/js/chunk-vendors.js' %}"></script>
<script type="text/javascript" src="{% static 'vue/dist/js/app.js' %}"></script>
{% endblock %}

api/actions/templates/actions/coordinator_actions.html
{% extends 'layouts/coordinator.html' %}

{% load humanize %}
{% load actions %}
{% load static %}
{% load admin_urls %}


{% block 'content' %}
<div class="row">
  <div id="sideMenu" class="nav flex-column">
    <a class="nav-link" href="{% url 'actions:coordinator_dashboard' %}">Dashboard</a>
    <a class="nav-link" href="{% url 'actions:coordinator_actions' %}">Actions</a>
    <a class="nav-link" href="{% url 'admin:actions_referral_changelist' %}">Referrals</a>
    <a class="nav-link" href="{% url 'admin:users_resident_changelist' %}">Residents</a>
    <a class="nav-link" href="{% url 'admin:users_volunteer_changelist' %}">Volunteers</a>
    <a class="nav-link" href="{% url 'admin:actions_organisation_changelist' %}">Organisations</a>
    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
  </div>
  <div class="col">
    <div id="actionsList"></div>
  </div>
  
</div>
<script type="text/javascript" src="{% static 'vue/dist/js/chunk-vendors.js' %}"></script>
<script type="text/javascript" src="{% static 'vue/dist/js/app.js' %}"></script>
{% endblock %}

api/actions/templates/actions/create_action_referral.html
{% extends 'layouts/application.html' %}

{% load humanize %}
{% load actions %}
{% load static %}


{% block 'content' %}
<div id="addActionRef"></div>
<script type="text/javascript" src="{% static 'vue/dist/js/chunk-vendors.js' %}"></script>
        <script type="text/javascript" src="{% static 'vue/dist/js/app.js' %}"></script>
{% endblock %}

api/actions/templates/actions/dashboard.html
{% extends 'layouts/coordinator.html' %}

{% load humanize %}
{% load actions %}
{% load static %}
{% load admin_urls %}

{% block 'title' %}
  <h1 class="text-center container-fluid">Coordinator Dashboard<a href="./call" class="btn btn-lg btn-primary float-right">Start Call</a></h1>
  
{% endblock %}
{% block 'content' %}
<div class="row no-gutters">
  <div id="sideMenu" class="nav flex-column">
    <a class="nav-link" href="{% url 'actions:coordinator_actions' %}">Actions</a>
    <a class="nav-link" href="{% url 'admin:actions_referral_changelist' %}">Referrals</a>
    <a class="nav-link" href="{% url 'admin:users_resident_changelist' %}">Residents</a>
    <a class="nav-link" href="{% url 'admin:users_volunteer_changelist' %}">Volunteers</a>
    <a class="nav-link" href="{% url 'admin:actions_organisation_changelist' %}">Organisations</a>
    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
  </div>
  <div class="col">
    <div class="row no-gutters">
      <div id="dashboard"></div>
    </div>    
  </div>
  
</div>
<script type="text/javascript" src="{% static 'vue/dist/js/chunk-vendors.js' %}"></script>
<script type="text/javascript" src="{% static 'vue/dist/js/app.js' %}"></script>
{% endblock %}

api/actions/templates/actions/detail.html
{% extends 'layouts/application.html' %}

{% load headings %}
{% load markdown %}
{% load svg %}

{% block 'title' %}
  <div class="action-header">
    <p class="action-header__id text-muted">Action <span aria-hidden="true">#</span>{{action.id}}</p>
    <h1 class="m-0">
      <span>{{action.help_type|title}}</span>
      ­-
      <span>{{action.ward|title}}
    </h1>
    <p class="text-center text-muted ">{{action.requested_datetime|date:"D d M H:i"}}</p>
  </div>
{% endblock%}

{% block 'content' %}

{% if volunteer in action.assigned_volunteers.all and action.can_reveal_private_information %}
  {# FIXED assigned_volunteer #}
  <h2 class="maf-2">Resident details</h2>
  {% include './_resident_detail.html' with resident=action.resident %}
{% endif %}

<h2 class="maf-2">Action details</h2>
<div class="card">
  {% if volunteer in action.assigned_volunteers.all and action.can_reveal_private_information %}
    {# FIXED assigned_volunteer #}
    {% if action.private_description %}
    <div class="border-bottom p-3 space-3">
      {{action.private_description|escape|markdown|heading_level:3}}
    </div>
    {% endif %}
  {% endif %}
  {% if action.public_description %}
    <div class="p-3">
      {{action.public_description|escape|markdown|heading_level:3}}
    </div>
  {% endif %}
    {% if not action.is_fully_assigned %}
      <div class="p-3">
      {% include './_action_footer_unassigned.html' with action=action volunteer=volunteer%}
      </div>
    {%else %}
      {# FIXED assigned_volunteer #}
      {% if volunteer not in action.assigned_volunteers.all %}
        <p class="text-center p-3">Someone's on it, but thanks for thinking of it!</p>
      {% else %}
        {% if action.has_interest %}
          <p class="text-center p-3">Thanks for volunteering! We'll be back in touch soon!</p>
        {% elif action.can_give_feedback %}
          <div class="p-3">
            {% include './_action_footer_assigned_to_user.html'%}
          </div>
        {% else %}
          <p class="alert alert-success text-center border-0 rounded-inside-card">Thanks for helping!<br><a href="{% url 'actions:available' %}" class="btn btn-secondary mt-2">Back to Tasks</a></p>
        {% endif %}
      {% endif%}
    {% endif %}
</div>
{% include './_problem_help.html' with action=action volunteer=volunteer%}
{% endblock %}

api/actions/templates/actions/single_action.html
{% extends 'layouts/application.html' %}

{% load humanize %}
{% load actions %}
{% load static %}


{% block 'content' %}
<div id="singleActionView"></div>
<script type="text/javascript" src="{% static 'vue/dist/js/chunk-vendors.js' %}"></script>
        <script type="text/javascript" src="{% static 'vue/dist/js/app.js' %}"></script>
{% endblock %}

api/actions/templates/actions/stop_ongoing.html
{% extends 'layouts/application.html' %}

{% load svg %}
{% load crispy_forms_tags %}

{% block 'content' %}
<form class="card p-3" method="POST">
  {% csrf_token %}
  {% crispy form form.helper%}
  <button name="outcome" value="ok" class="btn btn-danger d-table mx-auto mt-4">
    Stop collaboration
  </button>  
</form>
{% include './_problem_help.html' with action=action volunteer=volunteer%}
{% endblock %}