api/actions/urls.py
from django.urls import path, include
from django.views.generic.base import RedirectView, TemplateView
#from rest_framework import routers
#from rest_framework.documentation import include_docs_urls
from . import views

# Routers
#router = routers.DefaultRouter()
#router.register(r'api', views.OldActionViewSet)

app_name = 'actions'
urlpatterns = [
    path('<int:action_pk>/', views.pkdetail, name="pkdetail"),
    path('available/', views.ActionsListView.as_view(list_type='available'),
         name="available"),
    path('completed/', views.ActionsListView.as_view(list_type='completed'),
         name="completed"),
    path('coordinator/', views.CoordinatorDashboardView.as_view(), name="coordinator_dashboard"),
    path('coordinator/actions/', views.CoordinatorActionsView.as_view(), name="coordinator_actions"),
    path('coordinator/call/', views.CoordinatorCallView.as_view(), name="coordinate_actions"),
    path('coordinator/call/add/', views.CoordinatorCreateActionReferralView.as_view(), name="add_actions"),
    path('coordinator/action/', views.CoordinatorSingleActionView.as_view(), name="single_action"),
    path('ongoing/', views.ActionsListView.as_view(
        list_type='ongoing'), name="ongoing"),
    path('<action_uuid>/complete/', views.action_feedback, name="complete"),
    path('<action_uuid>/cancel/',
         views.stop_ongoing, name="cancel"),
#    path('api/', include((router.urls, 'app_name'))),
#    path('swagger-ui/', TemplateView.as_view(
#        template_name='api/swagger_ui.html',
#        extra_context={'schema_url':'openapi-schema'}),
#        name='swagger-ui'),
#    path('docs/', include_docs_urls(title='My API service'), name='api-docs'),
    path('<action_uuid>/', views.detail, name="detail"),
    path('', RedirectView.as_view(url='/'), name='index'),
]

api/tofro/urls.py
"""tofro URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from decorator_include import decorator_include
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from rest_framework.schemas import get_schema_view
from rest_framework import routers
from rest_framework.documentation import include_docs_urls


from tofro.views import LoginView, LogoutView, PasswordResetConfirmView, ToFroPasswordResetView, homepage, resolve_static_path_view
from tofro.lib import login_required
from users.views import UserSettingsView
from actions.views import ActionViewSet, ReferralViewSet, OrganisationViewSet, ActionFeedbackViewSet
from users.views import VolunteerViewSet, CoordinatorViewSet, ResidentViewSet, CurrentCoordinatorViewSet
from categories.views import HelpTypeViewSet, RequirementViewSet, WardViewSet, ReferralTypeViewSet

router2 = routers.SimpleRouter()
router2.register(r'actions', ActionViewSet)
router2.register(r'action_feedback', ActionFeedbackViewSet)
router2.register(r'referrals', ReferralViewSet)
router2.register(r'organisations', OrganisationViewSet)
router2.register(r'volunteers', VolunteerViewSet)
router2.register(r'coordinators', CoordinatorViewSet)
router2.register(r'current_coordinator', CurrentCoordinatorViewSet, basename='CurrentCoordinator')
router2.register(r'residents', ResidentViewSet)
router2.register(r'helptypes', HelpTypeViewSet)
router2.register(r'referraltypes', ReferralTypeViewSet)
router2.register(r'requirements', RequirementViewSet)
router2.register(r'wards', WardViewSet)

admin_path = settings.DJANGO_ADMIN_LOCATION + '/'

urlpatterns = [
    path('', homepage, name="home"),
    re_path(r'static-path/(?P<path>.+)', resolve_static_path_view),
    path(admin_path, admin.site.urls, name="admin"),
    # Take over the password reset confirmation with our own view
    path('accounts/reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password_reset/',
         ToFroPasswordResetView.as_view(), name='password_reset'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include((router2.urls, 'app_name'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('actions/', decorator_include(login_required, ('actions.urls', 'actions'))),
    path('accounts/login', LoginView.as_view(), name="login"),
    path('accounts/logout', LogoutView.as_view(), name="logout"),
    path('accounts/settings', UserSettingsView.as_view(), name='user-settings'),
    path('notifications/', include('notifications.urls')),
    path('docs/', include_docs_urls(title='My API service'), name='api-docs'),
    path('openapi', get_schema_view(
        title="Your Project",
        description="API for all things …",
        #permission_classes='IsAdminUser',
        version="1.0.0",
        url='/',
    ), name='openapi-schema'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + [
    re_path(r'^(?P<url>.*/)$', flatpage, name="page"),
]


# Add the debug toolbar.
if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

# Add Redis URLs.
urlpatterns += [
    path('django-rq/', include('django_rq.urls'))
]

api/core/views.py
from rest_framework import mixins, viewsets
from rest_framework.decorators import action

class BaseToFroViewSet(mixins.CreateModelMixin,
                   mixins.RetrieveModelMixin,
                   #mixins.UpdateModelMixin,
                   #mixins.DestroyModelMixin,
                   mixins.ListModelMixin,
                   viewsets.GenericViewSet):
    """
    A viewset that provides default `retrieve()` and `list()` actions.
    """
    pass

class IsInMixin():
    """
    A Django Rest Framework Viewset mixin that allows a list of pks to be passed and that lists only
    items with pks in that list
    """
    @action(methods=['get'], detail=False, url_path='isin/(?P<pks>[0-9,]+)')
    def isin(self, request, pks=None):
        pks = pks.split(',')
        pks = [int(pk) for pk in pks]
        self.queryset = self.queryset.filter(pk__in=pks)
        print(self.queryset.count())
        return self.list(request)

api/core/templates/layouts/_messages.html
{% load bootstrap %}
{% if messages %}
<ul class="list-unstyled">
    {% for message in messages %}
    <li{% if message.tags %} class="alert {{ message.tags|boostrap_theme_color:"alert" }}" {% endif %}>{{ message }}
        </li>
        {% endfor %}
</ul>
{% endif %}

api/core/templates/layouts/_page_links.html
<nav aria-labelledby="pagination">
  <h2 hidden id="pagination">Pages</h2>
  <ol class="pagination justify-content-center">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a>
    </li>
    {% endif %}
    <li class="page-item active">
      <a class="page-link" href="?page={{page.number}}" aria-current="true">{{page.number}}</a></li>
    {% if page.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a>
    </li>
    {% endif %}
  </ol>
</nav>

api/core/templates/layouts/application.html
{% load i18n %}
{% load static %}
{% load svg %}
{% load sitetree %}

{% autoescape on %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block 'page_title' %}
    {% if title %} {{title}} | {% endif %}
    {% endblock %}
    To/Fro</title>

  {% block extra_head %}
  {% endblock %}
  <script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
  <script src="{% url 'api-docs:schema-js' %}"></script>
  <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
   <script src="https://kit.fontawesome.com/3bb9809f03.js" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body {%if show_kites %}class="with-kites"{%endif%}>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">{% embed_svg 'static-src/img/svg/TO_FRO_logo-04-knockout.svg' width=70 height=32 role='img' %}</a>
    <button class="navbar-toggler ml-2 order-2 order-lg-1" type="button" data-toggle="collapse" data-target="#allNavigation" aria-controls="allNavigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-right text-lg-left order-3 order-lg-1" id="allNavigation">
      <nav id="leftNav" aria-labelledBy="leftNavHeading" >
          <h2 id="leftNavHeading" hidden>Main navigation</h2>
          {% sitetree_menu from "main_navigation" include "trunk" template "sitetree/menu_bootstrap4.html" %}
      </nav>
      {% if request.user.is_authenticated %}
      <nav class="mb-2 mb-lg-0 ml-auto" aria-labelledBy="accNavHeading">
        <h2 id="accNavHeading" hidden>Account navigation</h2>
        <ul id="rightNav" class="navbar-nav">
          {% if user.is_staff %}
          <li class="nav-item">
          </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="d-lg-none">Account</span>
                {% embed_fontawesome 'user' class_attribute="fa-lg" %}
            </a>
            <div class="dropdown-menu dropdown-menu-right text-right" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url 'actions:coordinator_dashboard' %}">Co-ordinator view</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'user-settings' %}">Account settings</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            </div>
          </li>
        </ul>
      </nav>

      {% endif %}
    </div>

  </nav>
  {% include './_messages.html' %}
  <main class="container-fluid container-lg py-5 space-4">
    <div class="heading-container d-flex justify-content-between">
      {% if back_url %}
      <a href="{{back_url}}" class="btn btn-icon-only rounded-circle align-self-start mt-2">
        {% embed_svg 'node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-left.svg' %}
        <span class="sr-only">Back</span>
      </a>
      {% endif %}
      {% block 'title' %}
        <h1 class="text-center mx-auto">
          {% block 'heading' %}
          {{heading|safe}}
          {% endblock %}
        </h1>
      {% endblock %}
      {% if back_url %}
      <a class="invisible btn btn-icon-only rounded-circle" role="presentation">
        {% embed_svg 'node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-left.svg' %}
      </a>
      {% endif %}
    </div>
    {% block 'content'%}{% endblock %}
  </main>
  <footer class="send-to-bottom site-footer">
    © 2021 To/Fro. {% sitetree_menu from "footer_navigation" include "trunk" %}
  </footer>
  <script>
      const coreapi = window.coreapi;
      const schema = window.schema;
      let auth = new coreapi.auth.SessionAuthentication({
            csrfCookieName: 'csrftoken',
            csrfHeaderName: 'X-CSRFToken',
        });
      let client = new coreapi.Client({auth: auth});
      let action = ["api", "list"];
            client.action(schema, action).then(function(result) {
            // Return value is in 'result'
      })
  </script>
</body>

</html>
{% endautoescape %}

api/core/templates/layouts/application_nosvg.html
{% load i18n %}
{% load static %}
{% load sitetree %}

{% autoescape on %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block 'page_title' %}
    {% if title %} {{title}} | {% endif %}
    {% endblock %}
    To/Fro</title>

  {% block extra_head %}
  {% endblock %}
  <script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
  <script src="{% url 'api-docs:schema-js' %}"></script>
  <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
   <script src="https://kit.fontawesome.com/3bb9809f03.js" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body {%if show_kites %}class="with-kites"{%endif%}>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/"></a>
    <button class="navbar-toggler ml-2 order-2 order-lg-1" type="button" data-toggle="collapse" data-target="#allNavigation" aria-controls="allNavigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-right text-lg-left order-3 order-lg-1" id="allNavigation">
      <nav id="leftNav" aria-labelledBy="leftNavHeading" >
          <h2 id="leftNavHeading" hidden>Main navigation</h2>
          {% sitetree_menu from "main_navigation" include "trunk" template "sitetree/menu_bootstrap4.html" %}
      </nav>
      {% if request.user.is_authenticated %}
      <nav class="mb-2 mb-lg-0 ml-auto" aria-labelledBy="accNavHeading">
        <h2 id="accNavHeading" hidden>Account navigation</h2>
        <ul id="rightNav" class="navbar-nav">
          {% if user.is_staff %}
          <li class="nav-item">
          </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="d-lg-none">Account</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right text-right" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url 'actions:coordinator_dashboard' %}">Co-ordinator view</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'user-settings' %}">Account settings</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            </div>
          </li>
        </ul>
      </nav>

      {% endif %}
    </div>

  </nav>
  {% include './_messages.html' %}
  <main class="container-fluid container-lg py-5 space-4">
    <div class="heading-container d-flex justify-content-between">
      {% if back_url %}
      <a href="{{back_url}}" class="btn btn-icon-only rounded-circle align-self-start mt-2">

        <span class="sr-only">Back</span>
      </a>
      {% endif %}
      {% block 'title' %}
        <h1 class="text-center mx-auto">
          {% block 'heading' %}
          {{heading|safe}}
          {% endblock %}
        </h1>
      {% endblock %}
      {% if back_url %}
      <a class="invisible btn btn-icon-only rounded-circle" role="presentation">

      </a>
      {% endif %}
    </div>
    {% block 'content'%}{% endblock %}
  </main>
  <footer class="send-to-bottom site-footer">
    © 2021 To/Fro. {% sitetree_menu from "footer_navigation" include "trunk" %}
  </footer>
  <script>
      const coreapi = window.coreapi;
      const schema = window.schema;
      let auth = new coreapi.auth.SessionAuthentication({
            csrfCookieName: 'csrftoken',
            csrfHeaderName: 'X-CSRFToken',
        });
      let client = new coreapi.Client({auth: auth});
      let action = ["api", "list"];
            client.action(schema, action).then(function(result) {
            // Return value is in 'result'
      })
  </script>
</body>

</html>
{% endautoescape %}

api/core/templates/layouts/coordinator.html
{% load i18n %}
{% load static %}
{% load svg %}
{% load sitetree %}


<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block 'page_title' %}
    {% if title %} {{title}} | {% endif %}
    {% endblock %}
    To/Fro</title>

  {% block extra_head %}
  {% endblock %}
  <script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
  <script src="{% url 'api-docs:schema-js' %}"></script>
  <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
   <script src="https://kit.fontawesome.com/3bb9809f03.js" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body {%if show_kites %}class="with-kites"{%endif%}>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">{% embed_svg 'static-src/img/svg/TO_FRO_logo-04-knockout.svg' width=70 height=32 role='img' %}</a>
    <button class="navbar-toggler ml-2 order-2 order-lg-1" type="button" data-toggle="collapse" data-target="#allNavigation" aria-controls="allNavigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-right text-lg-left order-3 order-lg-1" id="allNavigation">
      <nav id="leftNav" aria-labelledBy="leftNavHeading" >
          <h2 id="leftNavHeading" hidden>Main navigation</h2>
          {% sitetree_menu from "main_navigation" include "trunk" template "sitetree/menu_bootstrap4.html" %}
      </nav>
      {% if request.user.is_authenticated %}
      <nav class="mb-2 mb-lg-0 ml-auto" aria-labelledBy="accNavHeading">
        <h2 id="accNavHeading" hidden>Account navigation</h2>
        <ul id="rightNav" class="navbar-nav">
          {% if user.is_staff %}
          <li class="nav-item">
          </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="d-lg-none">Account</span>
                {% embed_fontawesome 'user' class_attribute="fa-lg" %}
            </a>
            <div class="dropdown-menu dropdown-menu-right text-right" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url 'actions:index' %}">Volunteer view</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'user-settings' %}">Account settings</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            </div>
          </li>
        </ul>
      </nav>

      {% endif %}
    </div>

  </nav>
  {% include './_messages.html' %}
  <main class="container-fluid py-5 space-4">
    <div class="heading-container d-flex justify-content-between">
      {% if back_url %}
      <a href="{{back_url}}" class="btn btn-icon-only rounded-circle align-self-start mt-2">
        {% embed_svg 'node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-left.svg' %}
        <span class="sr-only">Back</span>
      </a>
      {% endif %}
      {% block 'title' %}
        <h1 class="text-center mx-auto">
          {% block 'heading' %}
          {{heading|safe}}
          {% endblock %}
        </h1>
      {% endblock %}
      {% if back_url %}
      <a class="invisible btn btn-icon-only rounded-circle" role="presentation">
        {% embed_svg 'node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-left.svg' %}
      </a>
      {% endif %}
    </div>
    {% block 'content'%}{% endblock %}
  </main>
  <footer class="send-to-bottom site-footer">
    © 2021 To/Fro. {% sitetree_menu from "footer_navigation" include "trunk" %}
  </footer>
  <script>
      const coreapi = window.coreapi;
      const schema = window.schema;
      let auth = new coreapi.auth.SessionAuthentication({
            csrfCookieName: 'csrftoken',
            csrfHeaderName: 'X-CSRFToken',
        });
      let client = new coreapi.Client({auth: auth});
      let action = ["api", "list"];
            client.action(schema, action).then(function(result) {
            // Return value is in 'result'
      })
  </script>
</body>

</html>

api/core/templates/layouts/email_base.html
{% load i18n %}
{% load static %}
{% load svg %}
{% load sitetree %}
{% load links %}

{% load inlinecss %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>To-Fro - {{title}}</title>
  <style type="text/css">
    a:visited .action-title {
      color: #555  !important;
    }

    a:visited .action {
      border-color: #555 !important;
    }

    a:visited {
      color: #555 !important;
    }

    .action-table a:visited {
      color: inherit !important;
    }
    @media (prefers-color-scheme: dark){
      a:visited .action-title {
        color: #ccc !important;
      }
    }
    #wrapper {
      background-image: url('{{ request | base_url }}{% static 'img/svg/TO_FRO_kites_01-04.svg' %}');
    }
  </style>
</head>
{% inlinecss "email-base.css" %}
<body style="margin: 0; padding: 0;">
  <div id="wrapper" width="100%" style="">
    {% block 'content'%}{% endblock %}
    <table id="footer" role="presentation" cellpadding="0" cellspacing="0" style="max-width: 590px; background-color:#d4edf9;" border="0" align="center">
      <tr>
        <td width="100%" align="left" style="padding: 30px 20px 60px 20px;">
          <p style="margin: 0;">If you no longer want to recieve these emails change your notification settings to <a href="#">unsubscribe here</a></p>
          <p style="">&copy; 2020 To/Fro. </p>
        </td>
      </tr>
    </table>
  </div>
</body>
{% endinlinecss %}
</html>

api/core/templates/layouts/old_email_base.html
{% load i18n %}
{% load static %}
{% load svg %}
{% load sitetree %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Actions Digest Email</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body {%if show_kites %}class="with-kites"{%endif%}>
  <main class="container container--small py-5 space-4">
    <div class="heading-container d-flex justify-content-between">
      {% if back_url %}
      <a href="{{back_url}}" class="btn btn-icon-only rounded-circle align-self-start mt-2">
        {% embed_svg 'node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-left.svg' %}
        <span class="sr-only">Back</span>
      </a>
      {% endif %}
      {% block 'title' %}
        <h1 class="text-center mx-auto">
          {% block 'heading' %}
          {{heading|safe}}
          {% endblock %}
        </h1>
      {% endblock %}
      {% if back_url %}
      <a class="invisible btn btn-icon-only rounded-circle" role="presentation">
        {% embed_svg 'node_modules/@fortawesome/fontawesome-free/svgs/solid/arrow-left.svg' %}
      </a>
      {% endif %}
    </div>
    {% block 'content'%}{% endblock %}
  </main>
  <footer class="send-to-bottom site-footer">
    © 2020 To/Fro. {% sitetree_menu from "footer_navigation" include "trunk" %}
  </footer>
</body>

</html>